---
README.md:
    name: "rabbitmq-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Build Status](http://drone.etna-alternance.net/github.com/etna-alternance/composer-rabbitmq-service-provider/status.svg?branch=master)](http://drone.etna-alternance.net/github.com/etna-alternance/composer-rabbitmq-service-provider)"
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6d68e78abc191000017/badge.svg)](https://www.versioneye.com/user/projects/53dde6d68e78abc191000017)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-rabbitmq-service-provider/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-rabbitmq-service-provider/?branch=master)"
